# global options
dist: xenial
language:
  - c
compiler:
  - gcc
cache:
  directories:
    - "${HOME}/persist"
env:
  global:
    - MAKEOPTS="-j4"
git:
  submodules: false

# define the successive stages
stages:
  - name: test

# define the jobs for the stages
# approx order of the jobs has longest running first to optimise total time
jobs:
  include:
    # check code formatting
    - stage: test
      os: linux
      dist: bionic
      name: "code formatting"
      before_install:
        - sudo apt-add-repository --yes --update ppa:pybricks/ppa
      install:
        - sudo apt-get install uncrustify python3-pip
        - uncrustify --version
        - pip3 install --user setuptools
        - pip3 install --user black
        - black --version
      script:
        - tools/codeformat.py
        - git diff --exit-code

    # esp32 w/ESP-IDFv3 port
    - stage: test
      name: "esp32 ESP-IDFv3 port build"
      install:
        - sudo apt-get install python3-pip
        - sudo pip3 install 'pyparsing<2.4'
        - curl -L https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz | tar zxf -
        - export PATH=$(pwd)/xtensa-esp32-elf/bin:$PATH
        - git clone https://github.com/espressif/esp-idf.git
        - export IDF_PATH=$(pwd)/esp-idf
      script:
        - make ${MAKEOPTS} -C mpy-cross
        - git -C esp-idf checkout $(grep "ESPIDF_SUPHASH_V3 :=" ports/esp32/Makefile | cut -d " " -f 3)
        - git -C esp-idf submodule update --init components/json/cJSON components/esp32/lib components/esptool_py/esptool components/expat/expat components/lwip/lwip components/mbedtls/mbedtls components/micro-ecc/micro-ecc components/nghttp/nghttp2 components/nimble components/bt
        - make ${MAKEOPTS} -C ports/esp32 submodules
        - make ${MAKEOPTS} -C ports/esp32

    # esp32 w/ESP-IDFv4 port
    - stage: test
      name: "esp32 ESP-IDFv4 port build"
      install:
        - sudo apt-get install python3-pip
        - sudo pip3 install 'pyparsing<2.4'
        - curl -L https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_2_0-esp-2019r2-linux-amd64.tar.gz | tar zxf -
        - export PATH=$(pwd)/xtensa-esp32-elf/bin:$PATH
        - git clone https://github.com/espressif/esp-idf.git
        - export IDF_PATH=$(pwd)/esp-idf
      script:
        - make ${MAKEOPTS} -C mpy-cross
        - git -C esp-idf checkout $(grep "ESPIDF_SUPHASH_V4 :=" ports/esp32/Makefile | cut -d " " -f 3)
        - git -C esp-idf submodule update --init components/bt/controller/lib components/bt/host/nimble/nimble components/esp_wifi/lib_esp32 components/esptool_py/esptool components/lwip/lwip components/mbedtls/mbedtls
        - make ${MAKEOPTS} -C ports/esp32 submodules
        - make ${MAKEOPTS} -C ports/esp32
